services:
  app:
    build:
      context: ./client
    ports:
      - 3000:5173 
    environment:
      - VITE_PROXY_STRING=http://api:4000 
    volumes: 
      - ./client:/app 
      - /app/node_modules
    depends_on:
      - api
  api:
    build:
      context: ./server
    ports: 
      - 4000:4000
    environment:
      - CONNECTION_URI_STRING=postgres://postgres:postgres@db:5432/planner
    volumes:
      - ./server:/api
      - /api/node_modules
    depends_on:
      - db
  db: 
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner
    volumes:
      - ./pg-data:/var/lib/postgresql/data # default path in the postgresql container (desc in docs)
