version: '3'
services:
  frontend:
    #command: sh -c "npm run dev"
    #working_dir: /app
    #depends_on:
    #  - api
    #image: node:18-alpine
    build: 
      context: ./client
      target: dev
    container_name: planner-frontend
    ports:
      - 3000:5173 
    #volumes: 
      #- /app/node_modules
      #- ./client/:/app/
  api:
    #command: sh -c "npm run start"
    #working_dir: /api
    #image: node:18-alpine
    build:
      context: ./server
      target: dev
    container_name: planner-api
    restart: always
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - CONNECTION_URI_STRING=postgres://postgres:postgres@db:5432/planner
    #volumes:
      #- /api/node_modules
      #- ./server/:/api
    depends_on:
      - redis-store
      - db
  redis-store:
    image: redis
    container_name: redis-store
    volumes:
      - redis-store:/data
    # Don't expose without a password, no password by default
    # ports:
  db: 
    image: postgres
    container_name: planner-db
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner
    volumes:
      # my-pg-data is mapped to default pg path in the postgresql container (desc in postgres image docs)
      - my-pg-data:/var/lib/postgresql/data 

volumes:
  my-pg-data:
  redis-store:
