version: '3'
services:
  frontend:
    image: node:18-alpine
    command: sh -c "npm run dev"
    container_name: planner-frontend
    working_dir: /app
    ports:
      - 3000:5173 
    volumes: 
      - ./client/:/app/
    depends_on:
      - api
  api:
    image: node:18-alpine
    container_name: planner-api
    command: sh -c "npm run start"
    ports:
      - 4000:4000
      - 9229:9229
    working_dir: /api
    environment:
      - CONNECTION_URI_STRING=postgres://postgres:postgres@db:5432/planner
      - JWT_SECRET=development
    volumes:
      - ./server/:/api
    depends_on:
      - redis-store
      - db
  redis-store:
    image: redis
    container_name: redis-store
    volumes:
      - redis-store:/data
    # Don't expose without a password, no password by default
    # ports:
  db: 
    image: postgres
    container_name: planner-db
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner
    volumes:
      # my-pg-data is mapped to default pg path in the postgresql container (desc in postgres image docs)
      - my-pg-data:/var/lib/postgresql/data 

volumes:
  my-pg-data:
  redis-store:
