version: '3'

services:
  web:
    container_name: planner-web
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL} 
    ports:
      - 3000:80
    networks:
      - my-network
  api:
    container_name: planner-api
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_URI: ${DB_URI} 
      SESS_SECRET: ${SESS_SECRET}
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - my-network
  redis-store:
    image: redis
    container_name: redis-store
    volumes:
      - redis-data:/data
    networks:
      - my-network
    # Don't expose without a password, no password by default
    # ports:
  db:
    image: postgres
    container_name: db
    restart: always
    # Password is only non-option env var
    environment:
      # Must add Postgres_DB and POSTGRES_PASSWORD
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  pg-data:
    name: pg-data
  redis-data:
    name: redis-data
networks:
  my-network:
    name: my-network
    external: true
