version: '3'
services:
  frontend:
    image: node:18-alpine
    container_name: planner-frontend
    command: sh -c "npm run dev"
    ports:
      - 127.0.0.1:3000:5173 
    working_dir: /app
    volumes: 
      - ./client/:/app 
    depends_on:
      - api
  api:
    image: node:18-alpine
    container_name: planner-api
    command: sh -c "npm run start"
    ports:
      - 127.0.0.1:4000:4000
    working_dir: /api
    environment:
      - CONNECTION_URI_STRING=postgres://postgres:postgres@db:5432/planner
      - JWT_SECRET=development
    volumes:
      - ./server/:/api
    depends_on:
      - db
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner
    volumes:
      # my-pg-data is mapped to default pg path in the postgresql container (desc in postgres image docs)
      - my-pg-data:/var/lib/postgresql/data 

volumes:
  my-pg-data:
