version: '3'
services:
  frontend:
    container_name: planner-frontend
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:5173 
    volumes: 
      - /app/node_modules
      - ./client/:/app/
    environment:
      VITE_API_URL: ${VITE_API_URL} 
  api:
    container_name: planner-api
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      DB_URI: ${DB_URI} 
      SESS_SECRET: ${SESS_SECRET}
    volumes:
      - /api/node_modules
      - ./server/:/api/
    depends_on:
      - redis-store
      - db
  redis-store:
    image: redis
    container_name: redis-store
    volumes:
      - redis-data:/data
    # Don't expose without a password, no password by default
    # ports:
  db: 
    image: postgres
    container_name: pg-db
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner
    volumes:
      # my-pg-data is mapped to default pg path in the postgresql container (desc in postgres image docs)
      - pg-data:/var/lib/postgresql/data 

volumes:
  pg-data:
  redis-data:
